#ifndef PROTECTORDEF_H
#define PROTECTORDEF_H

#define DEVICE_NAME     L"\\Device\\Protector"
#define SYMLINK_NAME    L"\\??\\Protector"
#define CREATE_FILE_NAME L"\\\\.\\Protector"

#define FAKE_PROCESS_NAME "cmd.exe"
#define FAKE_PROCESS_NAME_W L"cmd.exe"
#define FAKE_PROCESS_NTPATH_W L"\\Device\\HarddiskVolume3\\Windows\\System32\\cmd.exe"
#define FAKE_PROCESS_FILEOBJECT_FILENAME_W L"\\Windows\\System32\\cmd.exe"
#define FAKE_PROCESS_PATH_W L"C:\\Windows\\System32\\cmd.exe"
#define FAKE_WINDOW_NAME_W L"命令提示符"

#define IOCTL_PROT_PROCESS CTL_CODE(FILE_DEVICE_UNKNOWN, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_UNPROT_PROCESS CTL_CODE(FILE_DEVICE_UNKNOWN, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ADD_WHITE CTL_CODE(FILE_DEVICE_UNKNOWN, 0x802, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ADD_BLACK CTL_CODE(FILE_DEVICE_UNKNOWN, 0x803, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_REMOVE_WHITE CTL_CODE(FILE_DEVICE_UNKNOWN, 0x804, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_REMOVE_BLACK CTL_CODE(FILE_DEVICE_UNKNOWN, 0x805, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_NOTIFY_CREATE_PS CTL_CODE(FILE_DEVICE_UNKNOWN, 0x806, METHOD_BUFFERED, FILE_ANY_ACCESS)

typedef struct ProtectProcessInfo {
    char processName[16];
} ProtectProcessInfo;

#endif // PROTECTORDEF_H